config/routes.rb
Rails.application.routes.draw do
  get 'books/new'
  post 'books' => 'books#create'
  get 'books' => 'books#index'
  get 'books/:id' => 'books#show',as:'book'
  get 'books/:id/edit' => 'books#edit',as:'edit_book'
  patch 'books/:id' => 'books#update',as:'update_book'
  delete 'books/:id' => 'books#destroy',as:'destroy_book'
  root to: "books#top"
  get 'homes/top'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def top
  end

  def new

  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to book_path(@book.id)
      flash[:notice] = "Book was successfully created."
    else
      render:new
    end
  end

  def index
    @book = Book.new
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id)
      flash[:notice] = "Book was successfully updated."
    else
      render:edit
    end

  end

  def destroy
    @book = Book.find(params[:id])
    if @book.destroy
      redirect_to '/books'
      flash[:notice] = "Book was successfully destroyed."
    end
  end

  private
  def book_params
    params.require(:book).permit(:title,:body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<div id="error_explanation">
  <% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
</div>
<h1>Editing Book</h1>
<%= form_with model:@book,url:update_book_path(@book.id),method: :patch do |f|%>
  <div class = "field">
    <label for = "book_title">Title</label>
    <%= f.text_field:title %>
  </div>

  <div class = "field">
    <label for = "book_body">Body</label>
    <%= f.text_area:body %>
  </div>


  <%= f.submit'Update Book' %>
<% end %>
<%= link_to"Show",book_path(@book.id) %>
|
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id = "notice"><%= flash[:notice]%></p>

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th> Title </th>
      <th> Body </th>
      <th colspan = "3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |books| %>
      <tr>
        <td><%= books.title %></td>
        <td><%= books.body %></td>
        <td><%= link_to"Show",book_path(books.id) %></td>
        <td><%= link_to"Edit",edit_book_path(books.id) %></td>
        <td><%= link_to "Destroy", destroy_book_path(books.id), method: :delete, "data-confirm" => "Are you sure？" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<h2>New book</h2>
<div id="error_explanation">
  <% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
</div>


<%= form_with model:@book do |f| %>

   <div class = "field">
    <label for = "book_title">Title</label>
    <%= f.text_field:title %>
  </div>

  <div class = "field">
    <label for = "book_body">Body</label>
    <%= f.text_area:body %>
  </div>

  <div class = "action">
    <%= f.submit 'Create Book'%>
  </div>

<% end %>

app/views/books/new.html.erb
<h1>Books</h1>
<h2>New book</h2>

<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model:@book do |f| %>
  <h3>Title</h3>
  <%= f.text_field:title %>

  <h3>Body</h3>
  <%= f.text_area:body %>

  <%= f.submit 'Create Book'%>
<% end %>

app/views/books/show.html.erb
<p id = "notice"><%= flash[:notice]%></p>


<p>
    <strong>Title:</strong>
    <%= @book.title %>
</p>


<p>
   <strong>Body:</strong>
   <%= @book.body %>
</p>

<%= link_to"Edit",edit_book_path(@book.id) %>
|
<%= link_to 'Back', books_path %>

app/views/books/top.html.erb
<h1>
  ようこそ
  <strong>Bookers</strong>
  へ！
</h1>

<p>
  <strong>Bookers</strong>
  では、さまざまな書籍に関するあなたの意見や
  <p>印象を共有し交換することができます</p>
</p>
<p>
  <%= link_to 'start', books_path %>
</p>

app/views/homes/top.html.erb
<h1>Homes#top</h1>
<p>Find me in app/views/homes/top.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookersApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>